version: "3.9"

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMPOSE_PROJECT_NAME
      - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE_NAME=${POSTGRES_DATABASE_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PROJECT_NAME=${PROJECT_NAME}
    ports:
      - "${TELEGRAM_BOT_PORT}:${TELEGRAM_BOT_PORT}"
    volumes:
      - ~/.ssh:/root/.ssh
    command: npm start
