name: Digital Ocean Droplet Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Digital Ocean Droplet Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.TRUSTED_MACHINE_PRIVATE_SSH_ID_RSA }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          debug: true
          script: |
            rm -rf /usr/src/combiner-bot
            cd /usr/src
            git clone git@github.com:IvanStebletsov/combiner-bot.git
            cd /usr/src/combiner-bot/app
            export TELEGRAM_BOT_API_TOKEN=${{ secrets.TELEGRAM_BOT_API_TOKEN }}
            export TELEGRAM_BOT_PORT=${{ secrets.TELEGRAM_BOT_PORT }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_DATABASE_NAME=${{ secrets.POSTGRES_DATABASE_NAME }}
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            export COMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}
            export PROJECT_NAME=${{ secrets.PROJECT_NAME }}
            docker-compose up -d --build
